name: 'Scrub main.R function definitions'
description: Scrub main.R function definitions
inputs:
  input-path:
    description: path of the source main.R to scrub function defs from
    required: true
  output-path:
    description: path of the template main.R that has been scrubbed
    required: true
runs:
  using: 'composite'
  steps:
    - name: scrub main.R of function defs
      shell: bash
      run: python ${{ github.action_path }}/strip_main.py $PWD/${{ inputs.input-path }} > ${{ inputs.output-path }}
