name: 'Deploy assignment'
description: Deploy the current repo assignment materials to template-repo
inputs:
  template-repo:
    description: URL of the template repo this assignment should be deployed to
    required: true
runs:
  using: 'composite'
  steps:
    - name: check out the source repo
      uses: actions/checkout@v4
    - name: check out the template repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.template-repo }}
        path: 'template'
    - name: copy supported paths to template repo
      shell: bash
      run: cp README test_main.R report.Rmd reference_report.html template/
    - name: scrub main.R of function difs
      shell: bash
      run: echo scrubbing main.R...eventually
    - name: git add and git commit all changes in template repo, push
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        cd template
        git config user.email "bf591-deploy-action@i-am-a-robot.com.org"
        git config user.name "bf591-deploy-action"
        git add *
        git commit -m 'automated from ${{ github.ref }}'
        gh auth login
        git push
